# this is redis config file
[list]
    [list.default]
        proxy_list = ["39.100.68.202:6379"]
        conn_timeout = 500
        password = "8PKtAj9TDIuqAuAAL5w7"
        db = 0
        read_timeout = 1000
        write_timeout = 1000
        max_active = 200
        max_idle = 500